// Generated by gencpp from file gymnasium_env/Action.msg
// DO NOT EDIT!


#ifndef GYMNASIUM_ENV_MESSAGE_ACTION_H
#define GYMNASIUM_ENV_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gymnasium_env
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : action()  {
    }
  Action_(const ContainerAllocator& _alloc)
    : action(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::gymnasium_env::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gymnasium_env::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::gymnasium_env::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::gymnasium_env::Action > ActionPtr;
typedef boost::shared_ptr< ::gymnasium_env::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gymnasium_env::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gymnasium_env::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gymnasium_env::Action_<ContainerAllocator1> & lhs, const ::gymnasium_env::Action_<ContainerAllocator2> & rhs)
{
  return lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gymnasium_env::Action_<ContainerAllocator1> & lhs, const ::gymnasium_env::Action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gymnasium_env

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gymnasium_env::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gymnasium_env::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gymnasium_env::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gymnasium_env::Action_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gymnasium_env::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gymnasium_env::Action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gymnasium_env::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a70a7d92e0376dcb967914076f276ea6";
  }

  static const char* value(const ::gymnasium_env::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa70a7d92e0376dcbULL;
  static const uint64_t static_value2 = 0x967914076f276ea6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gymnasium_env::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gymnasium_env/Action";
  }

  static const char* value(const ::gymnasium_env::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gymnasium_env::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message sending action to env\n"
"\n"
"float32[] action\n"
;
  }

  static const char* value(const ::gymnasium_env::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gymnasium_env::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gymnasium_env::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gymnasium_env::Action_<ContainerAllocator>& v)
  {
    s << indent << "action[]" << std::endl;
    for (size_t i = 0; i < v.action.size(); ++i)
    {
      s << indent << "  action[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.action[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GYMNASIUM_ENV_MESSAGE_ACTION_H
