# bin_packing.yaml

panda_env_node:
  ros__parameters:
    objects: '{
      "cube_1": {
        "type": "red_cube",
        "position": [0.5,0.4,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "cube_2": {
        "type": "blue_cube",
        "position": [0.7,0.4,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "cube_3": {
        "type": "green_cube",
        "position": [0.9,0.4,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "bottle": {
        "type": "bottle",
        "position": [0.5,0.2,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "triangle": {
        "type": "yellow_triangle",
        "position": [0.7,0.2,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "cube_4": {
        "type": "green_cube",
        "position": [0.9,0.2,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },    

      "bin": {
        "type": "bin",
        "position": [0.7,-0.2,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }
    }'