# house_building_2.yaml

panda_env_node:
  ros__parameters:
    objects: '{
      "cube_1": {
        "type": "cube",
        "position": [0.7,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "cube_2": {
        "type": "cube",
        "position": [0.6,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "triangle": {
        "type": "long_yellow_triangle",
        "position": [0.6,0.2,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }
    }'