# house_building_3.yaml

panda_env_node:
  ros__parameters:
    objects: '{
      "cube_1": {
        "type": "red_cube",
        "position": [0.7,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "cube_2": {
        "type": "red_cube",
        "position": [0.6,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }

      "rectangle": {
        "type": "green_rectangle",
        "position": [0.8,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }

      "triangle": {
        "type": "yellow_long_triangle",
        "position": [0.6,0.2,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }
    }'