# stacking.yaml
panda_env_node:
  ros__parameters:
    objects: '{
      "cube": {
        "type": "red_cube",
        "position": [0.7,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "triangle": {
        "type": "yellow_triangle",
        "position": [0.6,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }
    }'