# move_cube.yaml
panda_env_node:
  ros__parameters:
    objects: '{
      "small_cube": {
        "type": "small_cube",
        "position": [0.7,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "big_cube": {
        "type": "blue_cube",
        "position": [0.6,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }
    }'