# move_cube.yaml
panda_env_node:
  ros__parameters:
    objects: '{
      "blue_cube": {
        "type": "blue_cube",
        "position": [0.7,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      },

      "red_cube": {
        "type": "red_cube",
        "position": [0.6,0.0,0.0],
        "orientation": [1.0,0.0,0.0,0.0]
      }
    }'